# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/statusservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import status_pb2 as proto_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/statusservice.proto',
  package='protoboilerplate',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19proto/statusservice.proto\x12\x10protoboilerplate\x1a\x12proto/status.proto2a\n\rStatusService\x12P\n\tGetStatus\x12\x1f.protoboilerplate.StatusRequest\x1a .protoboilerplate.StatusResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[proto_dot_status__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STATUSSERVICE = _descriptor.ServiceDescriptor(
  name='StatusService',
  full_name='protoboilerplate.StatusService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=67,
  serialized_end=164,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStatus',
    full_name='protoboilerplate.StatusService.GetStatus',
    index=0,
    containing_service=None,
    input_type=proto_dot_status__pb2._STATUSREQUEST,
    output_type=proto_dot_status__pb2._STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATUSSERVICE)

DESCRIPTOR.services_by_name['StatusService'] = _STATUSSERVICE

# @@protoc_insertion_point(module_scope)
